### ISSUE TITLE
chromsizes as a regular dict?

### ISSUE THREAD

**Issue by Phlya** [nvictus/pybbi#23]
Hi, bioframe doesn't understand OrderedDict as input to bf.from_any, and hence one can't just make a viewframe directly from the chromsizes read with bbi.
```
with bbi.open("file.bw") as f:
    view = bf.make_viewframe(f.chromsizes)
```

Since regular dicts are now sorted anyway, how about just using a regular dict?

**Comment by nvictus** [comment]
Probably good idea to change it yes, but there is no sensible reason that `bf.from_any` doesn't work with an ordered dict, since it is a subclass of dict.

The instance checking in bioframe needs to be fixed to use `isinstance` everywhere; this `type() == ` idiom is an antipattern: https://github.com/open2c/bioframe/blob/main/bioframe/core/construction.py

**Comment by Phlya** [comment]
That is also true...

**Comment by nvictus** [comment]
Changed to regular dict in #28 . But this type checking in bioframe really needs to be fixed before I close.

**Comment by nvictus** [comment]
Done!
